### ISSUE TITLE
[mid-v1.4/post-PE1] - roadmap - alexiscatnip

### ISSUE THREAD

**Issue by alexiscatnip** [CS2113-AY1819S1-W13-1/main#104]
- [x] Stay sane 
- [x] write tests for my enhancements -> [3-4 Nov]
- [x] fix bugs found in PE1 -> [3-4 Nov]

- [ ] (If all above are done) implement 'label' in TimeSlot Class.

**Comment by nianfei97** [comment]
I sincerely hope that the first checkbox stays ticked......
