### ISSUE TITLE
Security Feature Milestones V1.2 - V1.4

### ISSUE THREAD

**Issue by bennchong** [CS2113-AY1819S1-W13-1/main#24]
<h1>High-level overview of upcoming milestones: </h1>
<h2>v1.2</h2>

- [x] Login UI(hard coded users) Done #19 

- [x] Registration UI(Non-functional) done #37 

<h2>v1.3</h2>

- [x] Registration UI(Functional) done #40

- [x] Logout function done #40 

- [x] Transform it into CLI (CommandBox hide/display) done #40 

- [x] Login/Registration using actual database done #63 

- [x] Linking User:Security with person:Person done #40

- [x] Implementation of Security Exceptions done #63 

- [x] UG/DG (Design Considerations)

<h2>v1.4</h2>

- [x] Hashing of password #153

- [x] Implementation of ui command in commandparcer #153

- [x] passing of commands through security #153

- [ ] Login timeout feature

- [ ]  Use of other storage to increase efficiency (hashmap etc)

- [ ] admin features?

**Comment by cjinting-nus** [comment]
Do you want to close this soon?
