### ISSUE TITLE
v1.3 Task List (Nian Fei)

### ISSUE THREAD

**Issue by nianfei97** [CS2113-AY1819S1-W13-1/main#41]
Features
- [ ] Implement storage of timetables - to be handled by @alexiscatnip 
- [x] Create deconflicted timetable
- [x] Display deconflicted timetable
- [ ] Integration with select more than 1 feature - scapped
- [ ] Allow timeslots that do not start and end exactly on the hour - moved to v1.4

Testing
- [x] Create unit tests for deconflict command
- [ ] Re-implement broken storage unit & integration tests - to be handled by @alexiscatnip 
- [ ] Try to re-implement ~add and~ find system tests, abandon if deemed unfeasible (`add` is slated to be removed by v1.4)

Aesthetics
- [x] Create .css stylesheets for timeslots - changed implementation
- [x] Create separate colour scheme for deconflicted timetables
