### ISSUE TITLE
V1.3 Roadmap: (Alexis)

### ISSUE THREAD

**Issue by alexiscatnip** [CS2113-AY1819S1-W13-1/main#43]
**Import Feature
->Target completion date: October 19, 2018** 
- [x] Have come up with and decided on the desired design.
- [x] Can actually import timetable
- [x] Think about SRP-type improvements
- [ ] Implement unit tests for import classes
- [ ] completion

**Export Feature
->Target completion date: October 23, 2018 (mid V1.3)**
- [x] Have come up with and decided on the desired design.
- [x] Can actually export the timetable  (lacking: need to know what is acceptable formatting of ics)
- [x] Think about SRP-type improvements
- [ ] Implement unit tests for export.
- [ ] completion

**Save/Read TimeTable Feature (timetable information is saved across sessions)
->Target completion date: October 25, 2018** 
- [x] Have come up with and decided on the desired design.
- [ ] Is working: TimeTable information is saved across sessions.
- [ ] implemented tests
- [ ] completion

User guide/Dev guide->Target completion date: October 26, 2018
- [x]  finalise overall design of classes
- [ ]  write about implementation in Dev guide
- [ ] completion

**Comment by nianfei97** [comment]
Closed.

Please update/migrate remaining tasks to v1.4, thanks.
